name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main # 當推送到 main 分支時觸發

env:
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/course-mcp # Docker Hub 映像檔名稱

jobs:
  build-and-push:
    name: Build, Test, and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- 新增 Go 環境設定 ---
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3' # 確保這裡的 Go 版本與您的專案和 Dockerfile 中的版本一致

      # --- Linting 步驟 (目前已註解) ---
      # - name: Install golangci-lint
      #   run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      # - name: Run golangci-lint
      # #   run: |
      # #     go mod tidy
      # #     golangci-lint run ./...

      # --- 新增 Testing 步驟 ---
      - name: Run Go tests
        run: |
          go mod tidy # 確保所有依賴都已下載
          go test -v ./... # 執行所有單元測試

      # --- Docker Build 和 Push 步驟 ---
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:latest,${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}

